version: "3.8"
services:
  backend:
    container_name: dev_backend
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8092:8080"
    environment:
      - APP_ENV=dev
    depends_on:
      - dev_db
    networks:
      - dev-network
  dev_db:
    container_name: dev_db
    image: postgres:latest
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: app_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - dev-network
volumes:
  postgres-data-dev:
networks:
  dev-network:
    driver: bridge
